repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=.pylintrc"]
  - repo: local
    hooks:
      - id: pytest
        name: test
        entry: make
        args: ["test"]
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.960'
    hooks:
      - id: mypy
